version: '3'

services:
  app:
    container_name: django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate  &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres:10-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    # command: ["redis-server", "--appendonly", "yes"]
    # volumes:
    #   - redis_data:/data
    # ports:
    #   - "6379:6379"

  celery:
    container_name: celery
    build: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - app
      - db
      - redis
